/*
 * Copyright 2014 z.benrhouma.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.sofrecom;

import com.sofrecom.WorkflowService.ProcessGroupsMapping;
import java.awt.Container;

/**
 *
 * @author z.benrhouma
 */
public class WorkFlowExample extends javax.swing.JInternalFrame {

    public WorkFlowExample() {
        initComponents();
        WorkflowService.initWorkFlow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice = new javax.swing.ButtonGroup();
        selectedObject = new java.lang.Object();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        refuseDGBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        validateDCGPBtn = new javax.swing.JButton();
        valDFIBtn = new javax.swing.JButton();
        valFinalBtn = new javax.swing.JButton();
        vartaibleTextField = new javax.swing.JTextField();
        genReportBtn = new javax.swing.JButton();
        refuseDFIBtn = new javax.swing.JButton();
        refuseDCGPBtn = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Example of workflow");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 250, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Validation workflow");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jSeparator1.setPreferredSize(new java.awt.Dimension(1, 1));
        getContentPane().add(jSeparator1);

        jPanel2.setPreferredSize(new java.awt.Dimension(650, 400));

        jButton4.setText("start");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Variable");

        jTextField2.setText("Rapport commission distributeur");
        jTextField2.setEnabled(false);

        refuseDGBtn.setText("Refuse validation");
        refuseDGBtn.setEnabled(false);
        refuseDGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuseDGBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("VariableName");

        validateDCGPBtn.setText("validate DCGP = step(3||4)");
        validateDCGPBtn.setEnabled(false);
        validateDCGPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateDCGPBtnActionPerformed(evt);
            }
        });

        valDFIBtn.setText("validate DFI = step (3||4)");
        valDFIBtn.setEnabled(false);
        valDFIBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valDFIBtnActionPerformed(evt);
            }
        });

        valFinalBtn.setText("validate finale");
        valFinalBtn.setEnabled(false);
        valFinalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valFinalBtnActionPerformed(evt);
            }
        });

        vartaibleTextField.setText("10");
        vartaibleTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                vartaibleTextFieldCaretUpdate(evt);
            }
        });

        genReportBtn.setText("Produce Report (step1)");
        genReportBtn.setEnabled(false);
        genReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genReportBtnActionPerformed(evt);
            }
        });

        refuseDFIBtn.setText("Refuser la validation");
        refuseDFIBtn.setEnabled(false);
        refuseDFIBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuseDFIBtnActionPerformed(evt);
            }
        });

        refuseDCGPBtn.setText("Refuse validation");
        refuseDCGPBtn.setEnabled(false);
        refuseDCGPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuseDCGPBtnActionPerformed(evt);
            }
        });

        jButton5.setText("Workfow diagram");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45)
                        .addComponent(vartaibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(112, 112, 112)
                        .addComponent(jButton5)))
                .addContainerGap(340, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(refuseDCGPBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(validateDCGPBtn))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(valDFIBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refuseDFIBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(genReportBtn)
                        .addGap(277, 277, 277)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valFinalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refuseDGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(167, 167, 167))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vartaibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(35, 35, 35)
                .addComponent(refuseDCGPBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateDCGPBtn)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(genReportBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refuseDGBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valFinalBtn)
                        .addGap(61, 61, 61)))
                .addComponent(valDFIBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refuseDFIBtn)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel2);

        jSeparator2.setPreferredSize(new java.awt.Dimension(1, 1));
        getContentPane().add(jSeparator2);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 55));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 55));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(813, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WorkflowService.startProcess(vartaibleTextField.getText());
        refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void refuseDGBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuseDGBtnActionPerformed
        WorkflowService.validateDGTask(WorkflowService.ProcessTaskMapping.FINAL_VALDIATION, ProcessGroupsMapping.FINAL_VALDIATION, vartaibleTextField.getText(), false);
        refresh();
    }//GEN-LAST:event_refuseDGBtnActionPerformed

    private void validateDCGPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateDCGPBtnActionPerformed
        WorkflowService.validateDCGPTask(WorkflowService.ProcessTaskMapping.DCGP_VALIDATION, ProcessGroupsMapping.DCGP_VALIDATION, vartaibleTextField.getText(), true);
        refresh();
    }//GEN-LAST:event_validateDCGPBtnActionPerformed

    private void valDFIBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valDFIBtnActionPerformed
        WorkflowService.validateDFITask(WorkflowService.ProcessTaskMapping.DFI_VALIDATION, ProcessGroupsMapping.DFI_VALIDATION, vartaibleTextField.getText(), true);
        refresh();
    }//GEN-LAST:event_valDFIBtnActionPerformed

    private void valFinalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valFinalBtnActionPerformed
        WorkflowService.validateDGTask(WorkflowService.ProcessTaskMapping.FINAL_VALDIATION, ProcessGroupsMapping.FINAL_VALDIATION, vartaibleTextField.getText(), true);
        refresh();
    }//GEN-LAST:event_valFinalBtnActionPerformed

    private void vartaibleTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_vartaibleTextFieldCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_vartaibleTextFieldCaretUpdate

    private void genReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genReportBtnActionPerformed
        WorkflowService.generateReports(vartaibleTextField.getText());
        refresh();
    }//GEN-LAST:event_genReportBtnActionPerformed

    private void refuseDFIBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuseDFIBtnActionPerformed
        WorkflowService.validateDFITask(WorkflowService.ProcessTaskMapping.DFI_VALIDATION, ProcessGroupsMapping.DFI_VALIDATION, vartaibleTextField.getText(), false);
        refresh();
    }//GEN-LAST:event_refuseDFIBtnActionPerformed

    private void refuseDCGPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuseDCGPBtnActionPerformed
        WorkflowService.validateDCGPTask(WorkflowService.ProcessTaskMapping.DCGP_VALIDATION, ProcessGroupsMapping.DCGP_VALIDATION, vartaibleTextField.getText(), false);
        refresh();
    }//GEN-LAST:event_refuseDCGPBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        WorkflowDiagram example = new WorkflowDiagram();
        this.getParent().add(example);
        example.setVisible(true);     
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup choice;
    private javax.swing.JButton genReportBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton refuseDCGPBtn;
    private javax.swing.JButton refuseDFIBtn;
    private javax.swing.JButton refuseDGBtn;
    private java.lang.Object selectedObject;
    private javax.swing.JButton valDFIBtn;
    private javax.swing.JButton valFinalBtn;
    private javax.swing.JButton validateDCGPBtn;
    private javax.swing.JTextField vartaibleTextField;
    // End of variables declaration//GEN-END:variables

    private void refresh() {
        refreshGenerateReports();
        refreshValidationDCGP();
        refreshValidationDFI();
        refreshValidationFinale();
    }

    private void refreshGenerateReports() {
        if (WorkflowService.isValidTaskForCurrentProcess(WorkflowService.ProcessTaskMapping.GENERATE_REPORTS, WorkflowService.ProcessGroupsMapping.GENERATE_REPORTS, vartaibleTextField.getText())) {
            genReportBtn.setEnabled(true);

        } else {
            genReportBtn.setEnabled(false);
        }
    }

    private void refreshValidationDCGP() {
        if (WorkflowService.isValidTaskForCurrentProcess(WorkflowService.ProcessTaskMapping.DCGP_VALIDATION, WorkflowService.ProcessGroupsMapping.DCGP_VALIDATION, vartaibleTextField.getText())) {
            validateDCGPBtn.setEnabled(true);
            refuseDCGPBtn.setEnabled(true);
        } else {
            validateDCGPBtn.setEnabled(false);
            refuseDCGPBtn.setEnabled(false);

        }

    }

    private void refreshValidationDFI() {
        if (WorkflowService.isValidTaskForCurrentProcess(WorkflowService.ProcessTaskMapping.DFI_VALIDATION, WorkflowService.ProcessGroupsMapping.DFI_VALIDATION, vartaibleTextField.getText())) {
            valDFIBtn.setEnabled(true);
            refuseDFIBtn.setEnabled(true);

        } else {
            valDFIBtn.setEnabled(false);
            refuseDFIBtn.setEnabled(false);

        }

    }

    private void refreshValidationFinale() {
        if (WorkflowService.isValidTaskForCurrentProcess(WorkflowService.ProcessTaskMapping.FINAL_VALDIATION, WorkflowService.ProcessGroupsMapping.FINAL_VALDIATION, vartaibleTextField.getText())) {
            valFinalBtn.setEnabled(true);
            refuseDGBtn.setEnabled(true);

        } else {
            valFinalBtn.setEnabled(false);
            refuseDGBtn.setEnabled(false);
        }
    }

}
